/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WestfieldClientReportSetings.java
 *
 * Created on Oct 11, 2011, 11:57:45 AM
 */
package com.dramble;

import java.util.prefs.Preferences;

/**
 *
 * @author troy
 */
public class WestfieldClientReportSettings extends javax.swing.JDialog {

    /** Creates new form WestfieldClientReportSetings */
    public WestfieldClientReportSettings(java.awt.Frame parent) {
        super(parent);
        initComponents();
        isFirstRowReport1Columns.setSelected(prefs.getBoolean("isFirstRowColumns1", true));
        isFirstRowReport2Columns.setSelected(prefs.getBoolean("isFirstRowColumns2", true));
        primaryKey1.setText(prefs.get("primaryKey1", "2"));
        primaryKey2.setText(prefs.get("primaryKey2", "2"));
        column1.setText(prefs.get("column1", "4"));
        column2.setText(prefs.get("column2", "4"));
    }

    @Override
    public String toString() {
        return super.toString();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isFirstRowReport1Columns = new javax.swing.JCheckBox();
        isFirstRowReport2Columns = new javax.swing.JCheckBox();
        primaryKey1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        column1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        primaryKey2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        column2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.dramble.WestfieldClientReportApp.class).getContext().getResourceMap(WestfieldClientReportSettings.class);
        isFirstRowReport1Columns.setText(resourceMap.getString("isFirstRowReport1Columns.text")); // NOI18N
        isFirstRowReport1Columns.setName("isFirstRowReport1Columns"); // NOI18N
        isFirstRowReport1Columns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isFirstRowReport1ColumnsActionPerformed(evt);
            }
        });

        isFirstRowReport2Columns.setText(resourceMap.getString("isFirstRowReport2Columns.text")); // NOI18N
        isFirstRowReport2Columns.setName("isFirstRowReport2Columns"); // NOI18N
        isFirstRowReport2Columns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isFirstRowReport2ColumnsActionPerformed(evt);
            }
        });

        primaryKey1.setText(resourceMap.getString("primaryKey1.text")); // NOI18N
        primaryKey1.setName("primaryKey1"); // NOI18N
        primaryKey1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                primaryKey1FocusGained(evt);
            }
        });
        primaryKey1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                primaryKey1KeyReleased(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        column1.setText(resourceMap.getString("column1.text")); // NOI18N
        column1.setName("column1"); // NOI18N
        column1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                column1FocusGained(evt);
            }
        });
        column1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                column1KeyReleased(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        primaryKey2.setText(resourceMap.getString("primaryKey2.text")); // NOI18N
        primaryKey2.setName("primaryKey2"); // NOI18N
        primaryKey2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                primaryKey2FocusGained(evt);
            }
        });
        primaryKey2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                primaryKey2KeyReleased(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        column2.setText(resourceMap.getString("column2.text")); // NOI18N
        column2.setName("column2"); // NOI18N
        column2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                column2FocusGained(evt);
            }
        });
        column2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                column2KeyReleased(evt);
            }
        });

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        okButton.setText(resourceMap.getString("okButton.text")); // NOI18N
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isFirstRowReport2Columns)
                    .addComponent(isFirstRowReport1Columns)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(column1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(primaryKey1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(column2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(primaryKey2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(419, Short.MAX_VALUE)
                .addComponent(okButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isFirstRowReport1Columns)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primaryKey1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(column1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(isFirstRowReport2Columns)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primaryKey2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(column2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(okButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isFirstRowReport1ColumnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isFirstRowReport1ColumnsActionPerformed
        prefs.putBoolean("isFirstRowColumns1", isFirstRowReport1Columns.isSelected());
    }//GEN-LAST:event_isFirstRowReport1ColumnsActionPerformed

    private void isFirstRowReport2ColumnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isFirstRowReport2ColumnsActionPerformed
        prefs.putBoolean("isFirstRowColumns2", isFirstRowReport2Columns.isSelected());
    }//GEN-LAST:event_isFirstRowReport2ColumnsActionPerformed

    private void primaryKey1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_primaryKey1KeyReleased
        prefs.put("primaryKey1", primaryKey1.getText());
    }//GEN-LAST:event_primaryKey1KeyReleased

    private void column1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_column1KeyReleased
        prefs.put("column1", column1.getText());
    }//GEN-LAST:event_column1KeyReleased

    private void primaryKey2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_primaryKey2KeyReleased
        prefs.put("primaryKey2", primaryKey2.getText());
    }//GEN-LAST:event_primaryKey2KeyReleased

    private void column2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_column2KeyReleased
        prefs.put("column2", column2.getText());
    }//GEN-LAST:event_column2KeyReleased

    private void primaryKey1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_primaryKey1FocusGained
        primaryKey1.selectAll();
    }//GEN-LAST:event_primaryKey1FocusGained

    private void column1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_column1FocusGained
        column1.selectAll();
    }//GEN-LAST:event_column1FocusGained

    private void primaryKey2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_primaryKey2FocusGained
        primaryKey2.selectAll();
    }//GEN-LAST:event_primaryKey2FocusGained

    private void column2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_column2FocusGained
        column2.selectAll();
    }//GEN-LAST:event_column2FocusGained

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField column1;
    private javax.swing.JTextField column2;
    private javax.swing.JCheckBox isFirstRowReport1Columns;
    private javax.swing.JCheckBox isFirstRowReport2Columns;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField primaryKey1;
    private javax.swing.JTextField primaryKey2;
    // End of variables declaration//GEN-END:variables
    Preferences prefs = Preferences.userNodeForPackage(com.dramble.WestfieldClientReportApp.class);
}
